agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Agenda de Horários"
admin.site.index_title = "LavaCar - Agendamento de Horários"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('cliente.urls')),
    path('', include('funcionario.urls')),
    path('', include('produto.urls')),
    path('', include('servico.urls')),
    path('', include('atendimento.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atendimento/urls.py
from django.urls import path
from .views import AtendimentosView

urlpatterns = [
    path('atendimentos', AtendimentosView.as_view(), name='atendimentos'),
]

home/urls.py
from django.urls import path
from .views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

atendimento/models.py
from django.db import models

class Atendimento(models.Model):
    SITUACAO_OPCOES =(
        ('A', 'Agendado'),
        ('R', 'Realizado'),
        ('C', 'Cancelado'),
    )

    horario = models.DateTimeField('Horário', help_text='Data e hora do atendimento')
    cliente = models.ForeignKey('cliente.Cliente', verbose_name='Cliente',help_text='Nome do cliente', on_delete=models.CASCADE)
    funcionario = models.ForeignKey('funcionario.Funcionario', verbose_name='Funcionário', help_text='Nome do funcionário', on_delete=models.CASCADE)
    situacao = models.CharField('situação', max_length=15, help_text='Situação do atendimento', choices=SITUACAO_OPCOES, default='A')
    servico = models.ForeignKey('servico.Servico', verbose_name='Serviço',help_text='Nome do serviço', on_delete=models.CASCADE)


    class Meta:
        verbose_name = 'Atendimento'
        verbose_name_plural = 'Atendimentos'
        ordering = ['-horario', ]

    def __str__(self):
        return f'Cliente: {self.cliente} - Funcionario: {self.funcionario} - Servico: {self.servico}'

atendimento/forms.py
from django import forms

from atendimento.models import Atendimento
from cliente.models import Cliente
from funcionario.models import Funcionario
from servico.models import Servico

class AtendimentoListForm(forms.Form):
    SITUACAO_OPCOES = (
        ('T', '----------'),
        ('A', 'Agendado'),
        ('R', 'Realizado'),
        ('C', 'Cancelado')
    )

    cliente = forms.ModelChoiceField(label='Cliente:', widget=forms.Select(attrs={'class': 'select is-fullwidth '}), queryset=Cliente.objects.all(), required=False )

    funcionario = forms.ModelChoiceField(label='Funcionário:', widget=forms.Select(attrs={'class': 'select is-fullwidth'}), queryset=Funcionario.objects.all(), required=False)

    servico = forms.ModelChoiceField(label='Servico:', widget=forms.Select(attrs={'class': 'select is-fullwidth'}), queryset=Servico.objects.all(), required=False)

    situacao = forms.ChoiceField(label='Situação:', widget=forms.Select(attrs={'class': 'select is-fullwidth'}), choices=SITUACAO_OPCOES, required=False)
class AtendimentoModelForm(forms.ModelForm):
    class Meta:
      model = Atendimento
      fields = ['horario', 'cliente', 'funcionario', 'servico', 'situacao']
      widgets ={
          'horario': forms.DateTimeInput(
              attrs={'class': 'input', 'type':'text', 'placeholder':'Digite o horario'}),
          'cliente': forms.Select(
              attrs={'class':'input','type':'text', 'placeholder':'Selecione o cliente'}),
          'funcionario':forms.Select(
              attrs={'class': 'input', 'type': 'text', 'placeholder': 'Selecione o funcionário'}),
          'servico': forms.Select(
              attrs={'class': 'input', 'type': 'text', 'placeholder': 'Selecione o serviço'}),
          'situacao': forms.Select(
              attrs={'class': 'input', 'type': 'text', 'placeholder': 'Selecione a situação'}),
      }

atendimento/views.py
from django.views.generic import ListView
from .forms import AtendimentoListForm
from .models import Atendimento

class AtendimentosView(ListView):
    model = Atendimento
    template_name = 'atendimentos.html'

    def get_context_data(self, **kwargs):
        context = super(AtendimentosView, self).get_context_data(**kwargs)

        if self.request.GET:
            form = AtendimentoListForm(self.request.GET)
        else:
            form = AtendimentoListForm()

        context['form'] = form
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(AtendimentosView, self).get_queryset()

        if self.request.GET:
            form = AtendimentoListForm(self.request.GET)
            if form.is_valid():
                cliente = form.cleaned_data.get('cliente')
                funcionario = form.cleaned_data.get('funcionario')
                servico = form.cleaned_data.get('servico')
                situacao = form.cleaned_data.get('situacao')

                if cliente:
                    qs = qs.filter(cliente=cliente)

                if funcionario:
                    qs = qs.filter(funcionario=funcionario)

                if servico:
                    qs = qs.filter(servico=servico)

                if situacao != 'T':
                    qs = qs.filter(situacao__icontains=situacao)
        return qs

atendimento/templates/atendimentos.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="section has-background-link-light">
        <div class="container">
            <form action="#" method="GET">
                <div class="field is-grouped is-flex is-align-items-center is-flex-wrap-wrap">
                    <label class="label p-2 mt-2">{{ form.cliente.label }}</label>
                    <div class="control is-expanded">
                        {{ form.cliente }}
                    </div>

                    <label class="label p-2 mt-2">{{ form.funcionario.label }}</label>
                    <div class="control is-expanded">
                        {{ form.funionario }}
                    </div>

                    <label class="label p-2 mt-2">{{ form.servico.label }}</label>
                    <div class="control is-expanded">
                        {{ form.servico }}
                    </div>

                    <label class="label p-2 mt-2">{{ form.situacao.label }}</label>
                    <div class="control is-expanded">
                        {{ form.situacao }}
                    </div>

                    <div class="control">
                        <button type="submit" class="button is-link">
                            Buscar
                        </button>
                    </div>
                </div>
            </form>
{% if object_list %}
            <div style="text-align: center;">
                <h1 class="subtitle is-size-4">Agendamentos Cadastrados</h1>
            </div>
            <div class="table">
                <table class="table is-table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                    <thead>
                    <tr>
                        <th class="has-text-centered">Horário</th>
                        <th class="has-text-centered">Cliente</th>
                        <th class="has-text-centered">Funcionário</th>
                        <th class="has-text-centered">Serviço</th>
                        <th class="has-text-centered">Situação</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for agendamento in object_list %}
                    <tr>
                        <td> {{ agendamento.horario}}</td>
                        <td> {{ agendamento.cliente}}</td>
                        <td> {{ agendamento.funcionario}}</td>
                        <td> {{ agendamento.servico}}</td>
                        <td> {{ agendamento.get_situacao_display }}</td>
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
                <h2>Não existe agendamentos cadastrados!</h2>
            {% endif %}
        </div>
    </section>
{% endblock %}